-- MySQL Script generated by MySQL Workbench
-- Mon 17 Feb 2025 10:18:47 AM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TipoReporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TipoReporte` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TipoReporte` (
  `TipoReporteId` INT NOT NULL,
  `TipoReporte` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TipoReporteId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `UsuarioId` INT NOT NULL AUTO_INCREMENT,
  `NivelAcceso` INT NULL DEFAULT 0 COMMENT 'Define el nivel de Acceso de un usuario\n\n0 = User\n1 = ',
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UsuarioId`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE,
  UNIQUE INDEX `UsuarioId_UNIQUE` (`UsuarioId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Provincias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Provincias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Provincias` (
  `ProvinciaId` INT NOT NULL,
  `Provincia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ProvinciaId`),
  UNIQUE INDEX `ProvinciaNombre_UNIQUE` (`Provincia` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cantones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cantones` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cantones` (
  `CantonId` INT NOT NULL,
  `Canton` VARCHAR(45) NOT NULL,
  `ProvinciaId` INT NOT NULL,
  PRIMARY KEY (`CantonId`),
  INDEX `fk_Cantones_Provincias1_idx` (`ProvinciaId` ASC) VISIBLE,
  CONSTRAINT `fk_Cantones_Provincias1`
    FOREIGN KEY (`ProvinciaId`)
    REFERENCES `mydb`.`Provincias` (`ProvinciaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Distritos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Distritos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Distritos` (
  `DistritoId` INT NOT NULL,
  `Distrito` VARCHAR(45) NOT NULL,
  `CantonId` INT NOT NULL,
  PRIMARY KEY (`DistritoId`),
  INDEX `fk_Distritos_Cantones1_idx` (`CantonId` ASC) VISIBLE,
  CONSTRAINT `fk_Distritos_Cantones1`
    FOREIGN KEY (`CantonId`)
    REFERENCES `mydb`.`Cantones` (`CantonId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Calles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Calles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Calles` (
  `CalleId` INT NOT NULL,
  `NombreCalle` VARCHAR(45) NOT NULL,
  `DistritoId` INT NOT NULL,
  PRIMARY KEY (`CalleId`),
  INDEX `fk_Calles_Distritos1_idx` (`DistritoId` ASC) VISIBLE,
  CONSTRAINT `fk_Calles_Distritos1`
    FOREIGN KEY (`DistritoId`)
    REFERENCES `mydb`.`Distritos` (`DistritoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reporte` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Reporte` (
  `ReporteId` INT NOT NULL AUTO_INCREMENT,
  `Mensaje` VARCHAR(45) NULL,
  `CoordenadaX` FLOAT NOT NULL DEFAULT 0,
  `CoordenadaY` FLOAT NOT NULL DEFAULT 0,
  `Activo` TINYINT NOT NULL DEFAULT 1,
  `TipoReporteId` INT NOT NULL,
  `UsuarioId` INT NOT NULL,
  `DistritoId` INT NOT NULL,
  `CalleId` INT NOT NULL,
  PRIMARY KEY (`ReporteId`),
  INDEX `fk_Reporte_TipoReporte_idx` (`TipoReporteId` ASC) VISIBLE,
  INDEX `fk_Reporte_Usuarios1_idx` (`UsuarioId` ASC) VISIBLE,
  INDEX `fk_Reporte_Distritos1_idx` (`DistritoId` ASC) VISIBLE,
  INDEX `fk_Reporte_Calles1_idx` (`CalleId` ASC) VISIBLE,
  CONSTRAINT `fk_Reporte_TipoReporte`
    FOREIGN KEY (`TipoReporteId`)
    REFERENCES `mydb`.`TipoReporte` (`TipoReporteId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reporte_Usuarios1`
    FOREIGN KEY (`UsuarioId`)
    REFERENCES `mydb`.`Usuarios` (`UsuarioId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reporte_Distritos1`
    FOREIGN KEY (`DistritoId`)
    REFERENCES `mydb`.`Distritos` (`DistritoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reporte_Calles1`
    FOREIGN KEY (`CalleId`)
    REFERENCES `mydb`.`Calles` (`CalleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios_has_Distritos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuarios_has_Distritos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios_has_Distritos` (
  `Usuarios_UsuarioId` INT NOT NULL,
  `Distritos_DistritoId` INT NOT NULL,
  PRIMARY KEY (`Usuarios_UsuarioId`, `Distritos_DistritoId`),
  INDEX `fk_Usuarios_has_Distritos_Distritos1_idx` (`Distritos_DistritoId` ASC) VISIBLE,
  INDEX `fk_Usuarios_has_Distritos_Usuarios1_idx` (`Usuarios_UsuarioId` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_has_Distritos_Usuarios1`
    FOREIGN KEY (`Usuarios_UsuarioId`)
    REFERENCES `mydb`.`Usuarios` (`UsuarioId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_has_Distritos_Distritos1`
    FOREIGN KEY (`Distritos_DistritoId`)
    REFERENCES `mydb`.`Distritos` (`DistritoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
